plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dice.roadmap.display'
    compileSdk 34

    defaultConfig {
        applicationId "com.dice.roadmap.display"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
